import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col font-sans min-h-screen text-grey-darkest bg-grey-lighter">
          <Header />

          <div className="flex flex-col flex-1 max-w-xl mx-auto px-4 py-8 w-full leading-normal">
            {children}
          </div>
          <footer className="bg-grey-darkest">
            <div className="flex justify-between max-w-xl mx-auto p-4 text-sm">
              <p className="text-grey-lighter">
                Created by{" "}
                <a
                  href="https://sohara.com"
                  className="font-bold no-underline text-grey-lighter"
                >
                  Sean O&apos;Hara
                </a>
                &nbsp;
                <a
                  href="mailto:sohara@sohara.com"
                  className="no-underline text-grey-lightest"
                >
                  sohara@sohara.com
                </a>
              </p>

              <p>
                <a
                  href="https://github.com/sohara"
                  className="font-bold no-underline text-grey-lighter"
                >
                  GitHub
                </a>
              </p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
